FROM docker.io/library/alpine:3.18.3

RUN apk add --no-cache \
  imagemagick \
  ruby \
  ruby-rmagick \
  ruby-webrick

WORKDIR /app

COPY Gemfile app.rb split.rb .
COPY public ./public
COPY views ./views

RUN gem install \
  --no-document \
  --file Gemfile

EXPOSE 4567
CMD ruby app.rb
