FROM docker.io/library/alpine:3.18.3

RUN apk add --no-cache \
  bash \
  imagemagick \
  ruby \
  ruby-rmagick \
  ruby-webrick \
  zip
RUN gem install --no-document \
  sinatra

COPY app.rb split.rb /app
COPY public /app/public
COPY views /app/views
WORKDIR /app
EXPOSE 4567
CMD ruby app.rb
