FROM debian:bookworm-20230814
# Debian 12.1

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install \
    --assume-yes \
    --no-install-recommends \
    ruby \
    imagemagick \
    zip \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
  # ruby-rmagick
  # ruby-zip
RUN gem install --no-document \
  sinatra
# digest-crc  # for digest/crc32

COPY app.rb split.sh /app
COPY public /app/public
COPY views /app/views
WORKDIR /app
EXPOSE 4567
CMD ruby app.rb
